services:
  pastebin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pastebin-app
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
    environment:
      - TZ=Asia/Shanghai
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin
    restart: unless-stopped

networks:
  default:
    name: pastebin-network
