services:
  pastebin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pastebin-app
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
    volumes:
      # 持久化数据库文件
      - ./data:/app/backend/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/api/auth/check"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  default:
    name: pastebin-network
